# Generated by Django 5.0.1 on 2024-01-22 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0002_qoshish'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Qoshish',
            new_name='Ariza',
        ),
    ]
