# Generated by Django 5.0.1 on 2024-01-23 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0004_subcrise'),
    ]

    operations = [
        migrations.AddField(
            model_name='ariza',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
